name: Build and Publish Linting Tools
on:
  push:
    branches:
      - master
      - dev
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        registry-url: 'https://npm.pkg.github.com'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn

    - name: Run lerna
      run: yarn lerna bootstrap

    - name: Publish
      run: |
        version=`node -p "require('./lerna.json').version"`
        
        if [ "${{github.ref}}" == "refs/heads/master" ]
        then
          tag=latest
        
          # Tag the commit with the correct version
          git tag $version
          git push origin $version
        else
          if [ "${{github.ref}}" == "refs/heads/dev" ]
          then
            tag="dev"
          else
            tag="feat"
          fi
          sha=${{github.sha}}
          short_commit_hash=${sha:0:7}
          version=$version-$tag-${{github.run_number}}-$short_commit_hash
        fi
        
        yarn lerna publish $version \
        --dist-tag $tag \
        --no-verify-access \
        --no-git-tag-version \
        --no-push \
        -y
        
        echo Package published with version: ${version}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
